10:20:40.943 | [38;5;184mWARNING[0m | preprocess_cat - Still missing values in columns: ['age_level', 'city_development_index', 'var_1', 'user_depth']
10:20:41.011 | [38;5;184mWARNING[0m | preprocess_cat - 3019 rows still have missing 'is_click'. Dropping these rows.
10:21:27.302 | [38;5;184mWARNING[0m | preprocess_cat - Still missing values in columns: 528
10:21:28.181 | [38;5;160mERROR[0m   | Flow run[35m 'important-mule'[0m - Encountered exception during execution: TypeError("Data row contained incompatible types:\n{'product': 'C', 'campaign_id': 360936, 'webpage_id': 'missing', 'gender': 'missing', 'age_level': 3.0, 'user_depth': 3.0, 'city_development_index': 2.0, 'var_1': 0.0, 'product_category': 'missing', 'Day': 4.0, 'Hour': 17.0, 'Minute': 32.0, 'weekday': 1.0, 'campaign_duration_hours': 68.51666666666667} of type {'product': String, 'campaign_id': Number, 'webpage_id': String, 'gender': String, 'age_level': Number, 'user_depth': Number, 'city_development_index': Number, 'var_1': Number, 'product_category': String, 'Day': Number, 'Hour': Number, 'Minute': Number, 'weekday': Number, 'campaign_duration_hours': Number} is not assignable to {'product': None or String, 'campaign_id': None or Number, 'webpage_id': None or Number, 'gender': None or String, 'age_level': None or Number, 'user_depth': None or Number, 'city_development_index': None or Number, 'var_1': None or Number, 'product_category': None or Number, 'Day': None or Number, 'Hour': None or Number, 'Minute': None or Number, 'weekday': None or Number, 'campaign_duration_hours': None or Number}\nKey 'webpage_id':\n\tString not assignable to None or Number\n\t\tString not assignable to None\n\tand\n\t\tString not assignable to Number\nKey 'product_category':\n\tString not assignable to None or Number\n\t\tString not assignable to None\n\tand\n\t\tString not assignable to Number")
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 746, in run_context
    yield self
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1354, in run_flow_sync
    engine.call_flow_fn()
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 766, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test3.py", line 34, in preprocess_flow
    df_clean, X_train, X_test, y_train, y_test, fold_datasets = preprocessor.preprocess(df)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\preprocess_cat.py", line 254, in preprocess
    self.callback({
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test3.py", line 8, in wandb_callback
    wandb.log(metrics)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 441, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 383, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1895, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1602, in _log
    self._partial_history_callback(data, step, commit)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1432, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\interface\interface.py", line 674, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
                   ^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\utils.py", line 85, in val_to_json
    val = wandb.Table(dataframe=val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 242, in __init__
    self._init_from_dataframe(dataframe, columns, optional, dtype)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 299, in _init_from_dataframe
    self.add_data(*tuple(dataframe[col].values[row] for col in self.columns))
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 446, in add_data
    result_type = self._get_updated_result_type(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 470, in _get_updated_result_type
    raise TypeError(
TypeError: Data row contained incompatible types:
{'product': 'C', 'campaign_id': 360936, 'webpage_id': 'missing', 'gender': 'missing', 'age_level': 3.0, 'user_depth': 3.0, 'city_development_index': 2.0, 'var_1': 0.0, 'product_category': 'missing', 'Day': 4.0, 'Hour': 17.0, 'Minute': 32.0, 'weekday': 1.0, 'campaign_duration_hours': 68.51666666666667} of type {'product': String, 'campaign_id': Number, 'webpage_id': String, 'gender': String, 'age_level': Number, 'user_depth': Number, 'city_development_index': Number, 'var_1': Number, 'product_category': String, 'Day': Number, 'Hour': Number, 'Minute': Number, 'weekday': Number, 'campaign_duration_hours': Number} is not assignable to {'product': None or String, 'campaign_id': None or Number, 'webpage_id': None or Number, 'gender': None or String, 'age_level': None or Number, 'user_depth': None or Number, 'city_development_index': None or Number, 'var_1': None or Number, 'product_category': None or Number, 'Day': None or Number, 'Hour': None or Number, 'Minute': None or Number, 'weekday': None or Number, 'campaign_duration_hours': None or Number}
Key 'webpage_id':
        String not assignable to None or Number
                String not assignable to None
        and
                String not assignable to Number
Key 'product_category':
        String not assignable to None or Number
                String not assignable to None
        and
                String not assignable to Number
10:21:28.538 | [38;5;160mERROR[0m   | Flow run[35m 'important-mule'[0m - Finished in state [38;5;160mFailed[0m("Flow run encountered an exception: TypeError: Data row contained incompatible types:\n{'product': 'C', 'campaign_id': 360936, 'webpage_id': 'missing', 'gender': 'missing', 'age_level': 3.0, 'user_depth': 3.0, 'city_development_index': 2.0, 'var_1': 0.0, 'product_category': 'missing', 'Day': 4.0, 'Hour': 17.0, 'Minute': 32.0, 'weekday': 1.0, 'campaign_duration_hours': 68.51666666666667} of type {'product': String, 'campaign_id': Number, 'webpage_id': String, 'gender': String, 'age_level': Number, 'user_depth': Number, 'city_development_index': Number, 'var_1': Number, 'product_category': String, 'Day': Number, 'Hour': Number, 'Minute': Number, 'weekday': Number, 'campaign_duration_hours': Number} is not assignable to {'product': None or String, 'campaign_id': None or Number, 'webpage_id': None or Number, 'gender': None or String, 'age_level': None or Number, 'user_depth': None or Number, 'city_development_index': None or Number, 'var_1': None or Number, 'product_category': None or Number, 'Day': None or Number, 'Hour': None or Number, 'Minute': None or Number, 'weekday': None or Number, 'campaign_duration_hours': None or Number}\nKey 'webpage_id':\n\tString not assignable to None or Number\n\t\tString not assignable to None\n\tand\n\t\tString not assignable to Number\nKey 'product_category':\n\tString not assignable to None or Number\n\t\tString not assignable to None\n\tand\n\t\tString not assignable to Number")
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test3.py", line 40, in <module>
    preprocess_flow("data/raw/train_dataset_full.csv", "data/processed")
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flows.py", line 1392, in __call__
    return run_flow(
           ^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1511, in run_flow
    ret_val = run_flow_sync(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1356, in run_flow_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 331, in result
    raise self._raised
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 746, in run_context
    yield self
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1354, in run_flow_sync
    engine.call_flow_fn()
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 766, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test3.py", line 34, in preprocess_flow
    df_clean, X_train, X_test, y_train, y_test, fold_datasets = preprocessor.preprocess(df)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\preprocess_cat.py", line 254, in preprocess
    self.callback({
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test3.py", line 8, in wandb_callback
    wandb.log(metrics)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 441, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 383, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1895, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1602, in _log
    self._partial_history_callback(data, step, commit)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 1432, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\interface\interface.py", line 674, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
                   ^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\utils.py", line 85, in val_to_json
    val = wandb.Table(dataframe=val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 242, in __init__
    self._init_from_dataframe(dataframe, columns, optional, dtype)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 299, in _init_from_dataframe
    self.add_data(*tuple(dataframe[col].values[row] for col in self.columns))
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 446, in add_data
    result_type = self._get_updated_result_type(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\data_types\table.py", line 470, in _get_updated_result_type
    raise TypeError(
TypeError: Data row contained incompatible types:
{'product': 'C', 'campaign_id': 360936, 'webpage_id': 'missing', 'gender': 'missing', 'age_level': 3.0, 'user_depth': 3.0, 'city_development_index': 2.0, 'var_1': 0.0, 'product_category': 'missing', 'Day': 4.0, 'Hour': 17.0, 'Minute': 32.0, 'weekday': 1.0, 'campaign_duration_hours': 68.51666666666667} of type {'product': String, 'campaign_id': Number, 'webpage_id': String, 'gender': String, 'age_level': Number, 'user_depth': Number, 'city_development_index': Number, 'var_1': Number, 'product_category': String, 'Day': Number, 'Hour': Number, 'Minute': Number, 'weekday': Number, 'campaign_duration_hours': Number} is not assignable to {'product': None or String, 'campaign_id': None or Number, 'webpage_id': None or Number, 'gender': None or String, 'age_level': None or Number, 'user_depth': None or Number, 'city_development_index': None or Number, 'var_1': None or Number, 'product_category': None or Number, 'Day': None or Number, 'Hour': None or Number, 'Minute': None or Number, 'weekday': None or Number, 'campaign_duration_hours': None or Number}
Key 'webpage_id':
	String not assignable to None or Number
		String not assignable to None
	and
		String not assignable to Number
Key 'product_category':
	String not assignable to None or Number
		String not assignable to None
	and
		String not assignable to Number
