0:	learn: 0.5605156	test: 0.5598842	best: 0.5598842 (0)	total: 221ms	remaining: 3m 41s
100:	learn: 0.6297366	test: 0.5869262	best: 0.5921034 (27)	total: 10.8s	remaining: 1m 36s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.5921034239
bestIteration = 27

Shrink model to first 28 iterations.
0:	learn: 0.5633700	test: 0.5512899	best: 0.5512899 (0)	total: 60.9ms	remaining: 1m
100:	learn: 0.6393753	test: 0.5761143	best: 0.5927751 (22)	total: 10.6s	remaining: 1m 34s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.5927751008
bestIteration = 22

Shrink model to first 23 iterations.
0:	learn: 0.5794945	test: 0.5736668	best: 0.5736668 (0)	total: 156ms	remaining: 2m 35s
14:00:41.752 | [38;5;160mERROR[0m   | Task run 'train_model-c28' - Crash detected! Execution was aborted by an interrupt signal.
14:00:41.761 | [38;5;160mERROR[0m   | Task run 'train_model-c28' - Finished in state [91mCrashed[0m('Execution was aborted by an interrupt signal.')
14:00:41.764 | [38;5;160mERROR[0m   | Flow run[35m 'rose-fox'[0m - Crash detected! Execution was aborted by an interrupt signal.
14:00:42.044 | [38;5;160mERROR[0m   | Flow run[35m 'rose-fox'[0m - Finished in state [91mCrashed[0m('Execution was aborted by an interrupt signal.')
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 189, in <module>
    preprocess_and_train_flow(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flows.py", line 1392, in __call__
    return run_flow(
           ^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1511, in run_flow
    ret_val = run_flow_sync(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1354, in run_flow_sync
    engine.call_flow_fn()
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 766, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 171, in preprocess_and_train_flow
    train_results = train_model(
                    ^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\tasks.py", line 1035, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 1576, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 1387, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 828, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 109, in train_model
    return trainer.train_and_evaluate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\train.py", line 190, in train_and_evaluate
    model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 5245, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 2410, in _fit
    self._train(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5017, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5066, in _catboost._CatBoost._train
KeyboardInterrupt
